script:
- npm install
- grunt build
deploy:
  provider: heroku
  api_key:
    secure: WgPtxi7RguB5LfFaFDYPcOi5HPdNvavFxGd3GkfP+BYkAGYjMLQCREY//JeNJyo7sP5ZxE4fnFX7YXbnxY2Sw1dGitYCRZnzfNFUTYRY8Lm3fjWTPHDXghner8myqNl0aiN7iK3W3FmrYtYKDM5B0ngYpupT2CXQoFceYE4eoBCDrO72RRzAIUhXaTNta+TMoBO5G5skKtCyDl/tjOHbbpEIdOVB+taMQjJ6m4NIkN+fog6BxsO1vx+GRhRkVObnC7VvUoDWbXCIclUvXYqnHYtAhjY8FGmrSm6Uo0+IirTst2VxixSXBH20BnE2HwFvTUUT7a81hlshbvRWB/8MgBHkcioOhvhNQErUKTh4qoMP1wRDORDyZirE347ZaykXi72kXasfZlR35rpDydq3j9EIHegGGN/0myEM4JJyT9TeVohTn7JPnIM3csNaq49oMFekHq9odMPDZhJBsn8OX9CgaxXeA/K4WzhqWkZ5W6C3pt6YPdhCA4JcLq88jXVEJR9HwZPRCSDcTeTOq9TqP3b7OSrl3F+kZbgixD97bcB6A2Uv3dPTIvmXehwQ3eWNYT5U6mon0DZdL4ulke8gCCmnJeEPyCcv+n3OO7kDRUN4dI3gcHm/qTVZnLw1ahLZ1biSL5gvMB4sLuJ+L9atI+Nr1jgHusKFAuWi+UmPpkQ=
  app: sphero-developer-docs
  on:
    repo: orbotix/DeveloperDocumentation
    branch: master
